[build]
  command = "npm run generate"
  functions = ".output/server"
  publish = "dist"

[dev]
  command = "npm run dev"
  autoLaunch = true

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NITRO_PRESET = "netlify"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "no-cache"