[build]
  command = "npm run generate"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "npm run dev"
  autoLaunch = true

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "no-cache"