import type { City } from '~/types';

// Données des villes - définies directement ici pour éviter les problèmes SSR
// la version slugify est ici => cities.ts
const citiesData: City[] = [
  { name: 'Abengourou' },
  { name: 'Abidjan' },
  { name: 'Aboisso' },
  { name: 'Accra', country: 'Ghana', countryFlag: '🇬🇭' },
  { name: 'Adiaké' },
  { name: 'Adzopé' },
  { name: 'Agboville' },
  { name: 'Akoupé' },
  { name: 'Alépé' },
  { name: 'Bamako', country: 'Mali', countryFlag: '🇲🇱' },
  { name: 'Bangolo' },
  { name: 'Biankouma' },
  { name: 'Bingerville' },
  { name: 'Bobo', country: 'Burkina Faso', countryFlag: '🇧🇫' },
  { name: 'Bocanda' },
  { name: 'Bondoukou' },
  { name: 'Bouaflé' },
  { name: 'Bouaké' },
  { name: 'Boundiali' },
  { name: 'Conakry', country: 'Guinée', countryFlag: '🇬🇳' },
  { name: 'Cotonou', country: 'Bénin', countryFlag: '🇧🇯' },
  { name: 'Dabola', country: 'Guinée', countryFlag: '🇬🇳' },
  { name: 'Dabou' },
  { name: 'Daloa' },
  { name: 'Danané' },
  { name: 'Daoukro' },
  { name: 'Diawala' },
  { name: 'Dimbokro' },
  { name: 'Divo' },
  { name: 'Duékoué' },
  { name: 'Faranah', country: 'Guinée', countryFlag: '🇬🇳' },
  { name: 'Ferkessédougou' },
  { name: 'Fresco' },
  { name: 'Gabiadji' },
  { name: 'Gagnoa' },
  { name: 'Gbon' },
  { name: 'Grand-Bassam' },
  { name: 'Grand-Lahou' },
  { name: 'Guiglo' },
  { name: 'Hire' },
  { name: 'Issia' },
  { name: 'Jacqueville' },
  { name: 'Katiola' },
  { name: 'Kindia', country: 'Guinée', countryFlag: '🇬🇳' },
  { name: 'Kissidougou', country: 'Guinée', countryFlag: '🇬🇳' },
  { name: 'Korhogo' },
  { name: 'Kouto' },
  { name: 'Lakota' },
  { name: 'Lola' },
  { name: 'Lomé', country: 'Togo', countryFlag: '🇹🇬' },
  { name: 'Macenta', country: 'Guinée', countryFlag: '🇬🇳' },
  { name: 'Mamou', country: 'Guinée', countryFlag: '🇬🇳' },
  { name: 'Man' },
  { name: 'Niakara' },
  { name: 'Nielle' },
  { name: 'Nzérékoré', country: 'Guinée', countryFlag: '🇬🇳' },
  { name: 'Odienné' },
  { name: 'Ouaga', country: 'Burkina Faso', countryFlag: '🇧🇫' },
  { name: 'Ouangolodougou' },
  { name: 'Oumé' },
  { name: 'Pogo' },
  { name: 'San-Pédro' },
  { name: 'Sassandra' },
  { name: 'Séguéla' },
  { name: 'Sikasso', country: 'Mali', countryFlag: '🇲🇱' },
  { name: 'Sinfra' },
  { name: 'Soubré' },
  { name: 'Tabou' },
  { name: 'Tafiré' },
  { name: 'Tengréla' },
  { name: 'Tiassalé' },
  { name: 'Touba' },
  { name: 'Toumodi' },
  { name: 'Vavoua' },
  { name: 'Yamoussoukro' },
  { name: 'Zouan-Hounien' },
  { name: 'Zuénoula' },
  { name: 'Bonon' },
  { name: 'Guessabo' },
  { name: 'Ouaninou' },
  { name: 'Labé', country: 'Guinée', countryFlag: '🇬🇳' },
];


export const useCities = () => {
  return {
    cities: citiesData.sort((a, b) => a.name.localeCompare(b.name)),
  }
}
